- index.js
- test.js
Things I missed?
Should we also check `if (typeof key === 'string' && val === undefined)` and throw an error? Or should we allow to overwrite a value with `undefined`? Seems a valid use case...
> improve set input detection - fixes #8

- index.js
- readme.md
- test.js
The `4.x` version of `dot-prop` includes the ability to pass a default with the `.get()` function which will be returned if the property is not defined. I am using your module `electron-config` and would like this functionality included for the added convenience of setting a default configuration state when one has not been saved for the user.
> Add support for providing a default value with getter

- index.js
- package.json
- test.js
The usage of conf fails in the REPL environment because the `module.filename` is `null`. In order to play around with the current module's config, i added the search & use of a local `package.json` if it exists.
> Fix #11 by falling back to cwd

- index.js
Getting an linting error.
```
Unexpected mix of && and ||.
```
@sindresorhus Might need some help :)
---
Fixes #17
> Add module.parent fallback

- index.js
- test.js
For the issue raised in #21.
I think this solution is simple enough:
- Try to parse and return the data. If not, try and decrypt it.
- If decrypting fails, act the same as before (as if the file didn't exist, or there was a `SyntaxError`).
- Otherwise, if parsing worked - just continue as normal.
So, notable changes:
1. Users can now set `encryptionKey` without worrying about upgrading the store
2. If decryption fails, `Conf` will silently just return the defaults
> Check if data is unencrypted before encrypting

- index.js
- test.js
Fixes #25.
Not satisfied with the error message + type of error being thrown, but here's a first pass at solving the issue.
> Recommend `.delete()` when setting `undefined`

- index.js
- test.js
Fixes #32.
A couple of things worth noting:
- that `assert.deepEqual` call may be expensive, but hopefully less expensive than a file write.
- if a `new Conf` is instantiated, without any default properties, `conf.path` won't exist until `conf.set` is called.
> Avoiding always writing to disk upon instantiation

- index.js
- readme.md
- test.js
Since #35 is still open, I thought I could finally resolve it maintaining the current behavior (as of 2.0.0) of adding the 'nodejs' suffix by default.
The option for controlling it is called `projectSuffix`, but feel free to change it to something you think is more appropriate.
I added 3 test cases which should cover all the cases I thought of:
1. **compatibility**: maintain the 2.0.0 behavior when not specifying the `projectSuffix`, so it will add the 'nodejs' suffix;
2. **new**: specifying an empty string should disable the suffix;
3. **new**: specifying a custom suffix should just use it instead of 'nodejs'.
I also updated the README with the new option specifics (added an `Examples` subsection).
---
Fixes #35
> Add `projectSuffix` option

- index.js
- readme.md
- test.js
@sindresorhus I decided to move the PR from yeoman/configstore#60 to here per your suggestion.
I think I incorporated all of your feedback from that PR except I didn't do anything special if the user passes `JSON.stringify` for `serialize`, though because I think it would be surprising to the user for the method they passed to not actually be used. Why would someone override the default with the intent of preserving the default?
> Add `serialize` and `deserialize` options

- index.js
Current logic to derive the storage path unnecessarily attempts to locate and access a `package.json` file when you provide `projectName` or `cwd` as override options to the constructor. This PR fixes that bug.
**Expected:**: Creating a conf object with options `projectName` or `cwd` defined shouldn't cause the module to locate and access `package.json` file.
**Actual:** Creating a conf object with options `projectName` or `cwd` defined does cause the module to locate and access `package.json` file.
The bug is causing Mac App Store version of the Bitwarden application to hang on launch when there exists a `package.json` file in the user's home folder. See this PR for more information: https://github.com/sindresorhus/electron-store/issues/59
> Fix path derivation logic

- index.d.ts
- index.js
- index.test-d.ts
- package.json
- readme.md
- test.js
Fix https://github.com/sindresorhus/electron-store/issues/16
Use epoberezkin/ajv for JSON schema validation
> Add support for JSON schema

- index.d.ts
- index.js
- index.test-d.ts
- package.json
- readme.md
- test.js
Linked with: https://github.com/sindresorhus/electron-store/pull/84
> Add `.reset()` method

- index.js
Ever since version 3 pkg-up accepts the `cwd` argument as an object (instead of a plain string).
https://github.com/sindresorhus/pkg-up/commit/7b8d9cfc5d9f7bb47cb3e38359a0cfa0e92caedd#diff-168726dbe96b3ce427e7fedce31bb0bc
> Fix issue with package.json inference when using the `cwd` option

- package.json
- readme.md
- source/index.ts
Use atomically instead of writeFileAtomic. 
https://github.com/sindresorhus/electron-store/issues/103
> Use `atomically` package instead of `write-file-atomic`

- readme.md
- source/index.ts
- test/index.ts
> Fix `.clear()` behavior

- source/index.ts
- test/index.ts
Currently condition to use whether default value or undefined, is not accuracy.
```js
if (value) {
}
```
The if condition with plain object in condition field will return false on falsy value including zero number (0), empty string (""), and false value of boolean (false). which on this case it might be actual default value.
So I create new function to help checking existing of variable which will check only not undefined and not null value
> Fix `.reset()` to correctly handle falsy default values

- package.json
- source/index.ts
- test/index.ts
This PR fixes #140 by adding a dependency on `ajv-formats`, and adding the formats to the `Ajv` instance used to validate configs against the `schema` option.
A test has been added to catch the issue, and I don't think any documentation changes are necessary since the README already claims that it's possible to use AJV's formats.
> Add ajv-formats when a schema is used

- source/index.ts
Resolves #145 .
This PR allows to use `conf` inside a webworker and prevent the app from crashing.
As described in #145 , this is a quick-win solution which will allow to use conf easily from inside the webworker, later iteration will be needed to remove the part of `module.parent` and `require.cache[__filename]` entirely.
> Wrap require-cache part with try-catch

- source/index.ts
- test/index.ts
Fixes #108 and fixes https://github.com/sindresorhus/electron-store/issues/93
Adds a configuration option called `watchFile`.
Works exactly like `watch` but uses `fs.watchFile` instead of `fs.watch`, allowing the subscription to read changes in the file more than once.
```jsx
useEffect(()=>{
store.onDidChange('myKey', (newV, oldV) => {
console.log(`Changed from ${oldV} to ${newV}`)
})
},[])
```
Clearly slower (sometimes, benchmarking is unreliable 100/2000ms) than `watch` but the only way to truly watch a file in React (and possible other scenarios, but not tested).
> Fix issue with `onDidChange` not always being called

- source/index.ts
```
if (this.#options.accessPropertiesByDotNotation) {
return this._get(key, defaultValue);
}
return key in this.store ? this.store[key] : defaultValue;
```
If `accessPropertiesByDotNotation == false` && `key in this.store == true`, then getter `get store()` will be run twice.
1. `key in this.store` 
2. `this.store[key]`
> Avoid invoking store getter twice

- readme.md
- source/index.ts
- source/types.ts
- test/index.test-d.ts
This is a proposed implementation for #157. This adds a `mode` option, which is passed through to the underlying call to `fs.writeFileSync` or `atomically.writeFileSync`.
The default mode here (`0o666`) is the default mode for both `fs.writeFileSync` and `atomically.writeFileSync` so this should be a backwards-compatible change.
> Add `configFileMode` option

- source/types.ts
PR #158 added a new option, but improperly set up the typescript type. Now, all typescript applications which try and use `conf` run into something like this:
```
error TS2345: Argument of type '{ watch: true; }' is not assignable to parameter of type 'Options<Record<string, unknown>>'.
Property 'configFileMode' is missing in type '{ watch: true; }' but required in type 'Except<Options<Record<string, unknown>>, "configName" | "projectName" | "projectVersion" | "projectSuffix">'.
```
during typescript compilation. This PR fixes this by properly marking the option as optional.
> Fix the `configFileMode` option for TypeScript

- source/types.ts
`Conf` requires `T` have a constraint of `Record<string, any>`. In previous versions of TS, this error went undetected.
> Update types for TS 4.7

- readme.md
- source/index.ts
- source/types.ts
- test/index.test-d.ts
- test/index.ts
You can use `beforeMigration` callback for logging purposes, preparing migration data, etc.
`beforeMigration` callback will be called before the migration is executed.
It could be useful when u have multiple configs and you want to log the migration data for each config.
My example - I use multiple `electron-store`'s and its usefull to log all migrations via `electron-log` in single file for debugging purposes, its easier to understand what can cause issue. Probably its can be usefull for others
```ts
import Conf from 'conf';
console.log = someLogger.log;
const mainConfig = new Conf({
beforeMigration: (store, currentVersion, nextVersion) => {
console.log(`[main-config] migrate from ${currentVersion} -> ${nextVersion}`);
},
migrations: {
'0.4.0': store => {
// somethign that might broke …
```
> beforeMigration option

- package.json
Trying to use the ESM version of Conf I noticed imports and types could not get resolved by Typescript. It turns out that [the paths](https://github.com/sindresorhus/conf/commit/cea3d686ec7f7a940ea74b6d719f069efc1c80f0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R15-R16) in the `package.json` are not the right ones. I'm updating them in this PR.
Would it be possible to do a patch release once this PR gets merged?
Thanks 🙏🏼
> Fix paths in `package.json`'s exports

- readme.md
The rest of the properties in `options` are H4, so presumably `migrations` and `beforeEachMigration` are also H4.
> docs: Fix API docs hierarchy

- package.json
- readme.md
- source/index.ts
- source/types.ts
- test/index.test-d.ts
Fixes #188
This PR replaces usage of `Buffer` in favor of `Uint8Array`. This is done by taking a dependency on the `uint8array-extras` package.
I verified that the tests are passing locally and I have update the documentation in the docstrings & README file.
> feat: replace buffer with uint8array

- source/index.ts
There is a typo in the docblock
> docs: typo in docs

- source/index.ts
Defer validation until after migrations are applied so that the store can be updated to the current schema.
applies to #187
> fix: store failing validation after schema change

- source/index.ts
- test/index.test-d.ts
Fixes / Adds back in original changes from #182
The implementation isn't recognized by TypeScript to be a possible signature for the method, only the overloads will be.
* Adds in overload for dot notation
* Adds in type test
> Add TypeScript overload for `.delete()` to fix dot-notation typing

- readme.md
- source/index.ts
- source/types.ts
- test/index.ts
Fixes #80
Fixes #99 
Fixes #169
> Add `rootSchema` and `ajvOptions` options
